env:
  browser: true
  es2021: true

extends:
  - eslint:recommended

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  no-console: 0
  import/extensions: 0
  no-param-reassign: 0
  no-underscore-dangle:
    - error
    - allow:
        - __dirname
        - __filename
  no-undef: 0
